location voiture/examintp/Controllers/LocationController.cs
using examintp.Models;
using examintp.Models.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;

namespace examintp.Controllers
{
    public class LocationController : Controller
    {
        private readonly ILocationRepository _locationRepository;
        private readonly IVoitureRepository _voitureRepository;

        public LocationController(ILocationRepository locationRepository, IVoitureRepository voitureRepository)
        {
            _locationRepository = locationRepository;
            _voitureRepository = voitureRepository;
        }

        public IActionResult Index()
        {
            var locations = _locationRepository.GetAll();
            return View(locations);
        }

        public IActionResult Details(int id)
        {
            var location = _locationRepository.GetById(id);
            if (location == null)
            {
                return NotFound();
            }
            return View(location);
        }

        // GET: Location/Create
        public IActionResult Create()
        {
            var voitures = _voitureRepository.GetAll(); 
            ViewBag.VoitureId = new SelectList(voitures, "Id", "Matricule"); 

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Location location)
        {
            _locationRepository.Add(location);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {
            var location = _locationRepository.GetById(id);
            if (location == null)
                return NotFound();

            var voitures = _voitureRepository.GetAll()
                .Select(v => new {
                    v.Id,
                    Description = v.Marque + " - " + v.Matricule
                });

            ViewBag.VoitureId = new SelectList(voitures, "Id", "Description", location.VoitureId);

            return View(location);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Location location)
        {
            if (id != location.Id)
            {
                return BadRequest();
            }

            _locationRepository.Update(location);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int id)
        {
            var location = _locationRepository.GetById(id);
            if (location == null)
                return NotFound();

            return View(location);
        }

        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _locationRepository.Delete(id);
            return RedirectToAction("Index");
        }

    }
}

location voiture/examintp/Controllers/VoitureController.cs
namespace examintp.Controllers
{
	using examintp.Models;
	using examintp.Models.Repositories;
    using examintp.ViewModels;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
	using Microsoft.AspNetCore.Mvc.Rendering;
    using System;

    public class VoitureController : Controller
	{
		private readonly IVoitureRepository _voitureRepository;
        private readonly IWebHostEnvironment _env;
        public VoitureController(IVoitureRepository repo, IWebHostEnvironment env)
        {
            _voitureRepository = repo;
            _env = env;
        }
        public ActionResult Search(string val)
        {
            var result = _voitureRepository.FindByName(val);
            return View("Index", result);
        }
        public IActionResult Index()
		{
			var Voitures = _voitureRepository.GetAll();
			return View(Voitures);
		}

		public IActionResult Details(int id)
		{
			var Voiture = _voitureRepository.GetById(id);
			if (Voiture == null)
				return NotFound();

			return View(Voiture);
		}

		public IActionResult Create()
		{
			return View();
		}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(VoitureViewModel model)
        {
            string uniqueFileName = UploadImage(model.ImageFile);

            var voiture = new Voiture
            {
                Matricule = model.Matricule,
                Marque = model.Marque,
                Modele = model.Modele,
                Image = uniqueFileName
            };

            _voitureRepository.Add(voiture);
            return RedirectToAction("Index");
        }


        [NonAction]
        private string UploadImage(IFormFile file)
        {
            if (file == null) return null;

            string uploadsFolder = Path.Combine(_env.WebRootPath, "images");
            string uniqueFileName = Guid.NewGuid().ToString() + "_" + file.FileName;
            string filePath = Path.Combine(uploadsFolder, uniqueFileName);

            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                file.CopyTo(stream);
            }

            return uniqueFileName;
        }



        public IActionResult Edit(int id)
        {
            var voiture = _voitureRepository.GetById(id);
            if (voiture == null)
                return NotFound();

            var viewModel = new EditViewModel
            {
                VoitureId = voiture.Id,
                Matricule = voiture.Matricule,
                Marque = voiture.Marque,
                Modele = voiture.Modele,
                ExistingImage = voiture.Image
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(EditViewModel model)
        {
            var voiture = _voitureRepository.GetById(model.VoitureId);
            if (voiture == null)
                return NotFound();

            voiture.Matricule = model.Matricule;
            voiture.Marque = model.Marque;
            voiture.Modele = model.Modele;

            if (model.ImageFile != null)
            {
                // Delete old image
                if (!string.IsNullOrEmpty(model.ExistingImage))
                {
                    var oldImagePath = Path.Combine(_env.WebRootPath, "images", model.ExistingImage);
                    if (System.IO.File.Exists(oldImagePath))
                        System.IO.File.Delete(oldImagePath);
                }

                voiture.Image = UploadImage(model.ImageFile);
            }

            _voitureRepository.Update(voiture);
            return RedirectToAction("Index");
        }



        public IActionResult Delete(int id)
		{
			var voiture = _voitureRepository.GetById(id);
			if (voiture == null)
				return NotFound();

			return View(voiture);
		}

		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public IActionResult DeleteConfirmed(int id)
		{
			_voitureRepository.Delete(id);
			return RedirectToAction("Index");
		}
	}

}

location voiture/examintp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestionVoitures</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GestionVoitures.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GestionVoitures</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Voiture" asp-action="Index">Liste des voitures</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Location" asp-action="Index">Liste des locations</a>
                        </li>
                    </ul>

                    <!-- Search bar -->
                    <form class="d-flex" asp-controller="Voiture" asp-action="Search">
                        <input class="form-control me-sm-2" type="search" placeholder="Rechercher" name="val">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - GestionVoitures - <a asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>